language: minimal

services: docker

install:
    - travis_retry docker-compose build

script:
    - .travis/smoke-test.sh

if: |
    branch = master OR \
    branch =~ /^(?:[0-9]|[1-9][0-9]*)\.(?:[0-9]|[1-9][0-9]*)$/ OR \
    tag IS present OR \
    type = pull_request
