version: '3.4'

services:
  run-tests:
    build:
      context: .
      target: dev
    entrypoint: ""
    volumes:
      - ./tests/:/airflow/tests/
      - ./dags:/airflow/dags/
      - ./config/aws_dev_config:/airflow/.aws/config
      - ./config/aws_dev_credentials:/airflow/.aws/credentials
      - ./config/airflow.test.cfg:/airflow/airflow.cfg
      - ./node-dependencies/package.json:/airflow/package.json
      - ./node-dependencies/package-lock.json:/airflow/package-lock.json
    command: /bin/sh -c "airflow initdb && pytest --disable-socket tests/"
    ports:
      - "9229:9229"  # nodejs debug port
