version: "3.4"

services:
  localstack-s3:
    image: localstack/localstack:latest
    environment:
      - PORT_WEB_UI=8081
      - DEFAULT_REGION=eu-west-2
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "8081:8081"

  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: airflow-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    build:
      target: dev
      context: .
    volumes:
      - ./airflow.cfg:/src/airflow/airflow.cfg
    ports:
      - 8080:8080
    depends_on:
      - db
