version: "3.4"

services:
  s3:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ACCESS_KEY: longkey
      MINIO_SECRET_KEY: verysecretkey
    ports:
      - 9000:9000

  awscli:
    build:
      context: .
      dockerfile: Dockerfile.awscli
    working_dir: /src/app
    volumes:
      - ./scripts/create-s3-buckets.sh:/src/app/create-s3-buckets.sh
      - ./tests/assets/:/src/app/assets/
    command: ./create-s3-buckets.sh
    depends_on:
      - s3
    environment:
      WAIT_HOSTS: s3:9000
      AWS_ACCESS_KEY_ID: longkey
      AWS_SECRET_ACCESS_KEY: verysecretkey

  message-bus:
    image: redis:5.0.5-alpine
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6379"]

  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: airflow-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

# only used to tag the base image ready to be uploaded to dockerhub
  app:
    build:
      target: base
      context: .
      args:
        revision: ${IMAGE_REVISION:-master}
    image: libero/jats-ingester:${IMAGE_TAG:-master}
    command: sh

  airflow_initdb:
    &airflow
    build:
      target: dev
      context: .
    command: upgradedb
    depends_on:
      - app
      - db
    environment:
      WAIT_HOSTS: db:5432, message-bus:6379
      AIRFLOW_CONN_REMOTE_LOGS: http://s3:9000?host=http://s3:9000
    volumes:
      - ./dags:/airflow/dags
      - ./config/aws_dev_config:/airflow/.aws/config
      - ./config/airflow.dev.cfg:/airflow/airflow.cfg

  airflow_webserver:
    <<: *airflow
    command: webserver -p 8080
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "python ./scripts/airflow_webserver_healthcheck.py"]

  airflow_scheduler:
    <<: *airflow
    command: scheduler

  airflow_worker:
    <<: *airflow
    command: worker
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8793'"]
      interval: 30s
      timeout: 30s
      retries: 3

  content-store:
    build:
      context: .
      target: dev
    entrypoint: ""
    volumes:
      - ./content-store.py:/airflow/content-store.py
    command: python /airflow/content-store.py

  search:
    build:
      context: .
      target: dev
    entrypoint: ""
    volumes:
      - ./search.py:/airflow/search.py
    command: python /airflow/search.py
